project:
  type: default
  output-dir: output

format:
  html:
    theme: cosmo
    mainfont: "Roboto"
    fontsize: 1rem
    linestretch: 1.6
    toc: true
    toc-depth: 3
    number-sections: false
    css: styles.css
    embed-resources: true
    self-contained-math: true
    fig-width: 7
    fig-height: 5
    fig-dpi: 150
  pdf:
    documentclass: article
    mainfont: "Roboto"
    fontsize: 11pt
    linestretch: 1.4
    toc: true
    number-sections: false
    fig-width: 7
    fig-height: 5

jupyter: python3

execute:
  echo: false
  warning: false
  message: false
